services:
  - type: web
    name: telegram-autopost-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python autopost_bot.py"
    autoDeploy: true
